# workflow:
#     - publish

jobs:
    main:
        steps:
            install: npm install
            test: npm test
            hostname: echo "hostname"

    # publish:
    #     steps:
    #         configure: ./scripts/configure
    #         install: npm install
    #         bump: npm run bump
    #         publish: npm publish && git push origin --tags -q
